version: '3.9'

services:

  app:
    build: .
    container_name: mystogan_app

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/mystogan_erp

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16

    container_name: mystogan_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mystogan_erp

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5